[debug]
address = "0.0.0.0"
port = 80
workers = 16
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
temp_dir = "D:\\workspace\\rust\\Nifties-server\\temp"
 

 
[release]
address = "0.0.0.0"
port = 80
workers = 128
keep_alive = 10
log = "off"
secret_key = "nKLiGJThxey3v1npBVtXNfr3PQsH50r6c/TSv47nuio="
limits = { forms = 32768 }
temp_dir = "/temp"